---
name: "AzureIllusion Subtitles"
guid: "c0beec43-85b2-4d2a-89a3-d3c50974b914"

version: "0.1.0.0"
targetAbi: "10.11.11.0"
framework: "net9.0"

owner: "i3lackhawk"

overview: "Polskie napisy z serwisu AzureIllusion."

description: >
  Wtyczka umożliwia wyszukiwanie i pobieranie polskich napisów
  z serwisu AzureIllusion bezpośrednio w Jellyfin.

category: "Subtitles"

artifacts:
  - "Jellyfin.Plugin.AzureIllusion.dll"

changelog: |-
  - Pierwsza publiczna wersja wtyczki.
  - Dodano obsługę wyszukiwania napisów.
  - Dodano pobieranie napisów z API AzureIllusion.
