name: "AzureIllusion Subtitles"
guid: "c0beec43-85b2-4d2a-89a3-d3c50974b914"

version: "0.1.0.0"
targetAbi: "10.11.11.0"
framework: "net9.0"

owner: "i3lackhawk"
category: "Subtitles"

overview: "Polskie napisy z serwisu AzureIllusion."

description: >
  Wtyczka pobiera polskie napisy z API serwisu
  AzureIllusion bezpośrednio do Jellyfin.

artifacts:
  - "Jellyfin.Plugin.AzureIllusion.dll"

changelog: |
  Pierwsza wersja wtyczki AzureIllusion.
