name: Deploy Jellyfin Plugin Repo

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Pakujemy plik dokładnie pod taką nazwą, jakiej szuka bot w logach
      - name: Package Plugin
        run: |
          mkdir -p build
          zip -j jellyfin-plugin-azureillusion-subtitles-polish.zip Jellyfin.Plugin.AzureIllusion.dll

      - name: Jellyfin Repo Manifest Manager
        uses: LizardByte/jellyfin-plugin-repo@v2026.602.212143
        with:
          action: add
          zipfile: jellyfin-plugin-azureillusion-subtitles-polish.zip
          github_token: ${{ secrets.GITHUB_TOKEN }}
